/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Fri Aug 07 2022 02:50:27 GMT-0700 (Pacific Daylight Time).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames
) {

    'use strict';

    function PetriNetVisualizerControl(options) {

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        // Initialize core collections and variables
        this._widget = options.widget;

        this._currentNodeId = null;
        this._currentNodeParentId = undefined;

        this._networkRootLoaded = false;

        this._fireableEvents = null;

        this._initWidgetEventHandlers();

        this.setFireableEvents = this.setFireableEvents.bind(this);

        this._logger.debug('ctor finished');
    }

    PetriNetVisualizerControl.prototype._initWidgetEventHandlers = function () {
        this._widget.onNodeClick = function (id) {
            // Change the current active object
            WebGMEGlobal.State.registerActiveObject(id);
        };
    };

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    PetriNetVisualizerControl.prototype.selectedObjectChanged = function (nodeId) {
        var desc = this._getObjectDescriptor(nodeId),
            self = this;

        self._logger.debug('activeObject nodeId \'' + nodeId + '\'');

        // Remove current territory patterns
        if (self._currentNodeId) {
            self._client.removeUI(self._territoryId);
            self._networkRootLoaded = false;
        }

        self._currentNodeId = nodeId;

        if (typeof self._currentNodeId === 'string') {
            // Put new node's info into territory rules
            self._selfPatterns = {};
            self._selfPatterns[nodeId] = {children: 1};  // Territory "rule"

            self._territoryId = self._client.addUI(self, function (events) {
                self._eventCallback(events);
            });

            // Update the territory
            self._client.updateTerritory(self._territoryId, self._selfPatterns);
        }
    };

    // This next function retrieves the relevant node information for the widget
    PetriNetVisualizerControl.prototype._getObjectDescriptor = function (nodeId) {
        var node = this._client.getNode(nodeId),
            objDescriptor;
        if (node) {
            objDescriptor = {
                id: node.getId(),
                name: node.getAttribute(nodePropertyNames.Attributes.name),
                childrenIds: node.getChildrenIds(),
                parentId: node.getParentId(),
                isConnection: GMEConcepts.isConnection(nodeId)
            };
        }

        return objDescriptor;
    };

    /* * * * * * * * Node Event Handling * * * * * * * */
    PetriNetVisualizerControl.prototype._eventCallback = function (events) {
        const self = this;
        console.log(events);
        events.forEach(event => {
            if (event.eid && 
                event.eid === self._currentNodeId ) {
                    if (event.etype == 'load' || event.etype == 'update') {
                        self._networkRootLoaded = true;
                    } else {
                        self.clearPetriNet();
                        return;
                    }
                }
                
        });

        // when the event received is of type complete, initialize the PetriNet
        if (events.length && events[0].etype === 'complete' && self._networkRootLoaded) {
            self._initPetriNet();
        }       
    };

    PetriNetVisualizerControl.prototype._initPetriNet = function () {
        const self = this;
        //get the raw meta from all nodes
        const rawMETA = self._client.getAllMetaNodes();
        const META = {};
        rawMETA.forEach(node => {
            // for each node get the nodeId and store it in the META
            META[node.getAttribute('name')] = node.getId();
        });
        self._logger.debug( "_initPetriNet::META " + JSON.stringify( META ) );
        //Collect the data for the visualization
        const pnNode = self._client.getNode(self._currentNodeId);
        const elementIds = pnNode.getChildrenIds();
        const pn = {
            init: null, 
            places:{}, 
            transitions: {},
        };
        this._processPlacesAndTransitions( pn, META, elementIds );
        this._processLinks( pn, META, elementIds );        
        pn.setFireableEvents = this.setFireableEvents;

        self._widget.initPetriNet(pn);
    };

    // Cleare the petriNet
    PetriNetVisualizerControl.prototype.clearPetriNet = function () {
        const self = this;
        self._networkRootLoaded = false;
        self._widget.destroyPetriNet();
    };

    PetriNetVisualizerControl.prototype._processPlacesAndTransitions = function( 
        pnModel, meta, webgmeElementIds 
    ) {
        const self = this;
        const pn = pnModel;
        const elementIds = webgmeElementIds;
        const META = meta;
        elementIds.forEach(elementId => {
            const node = self._client.getNode(elementId);
            // the simple way of checking type
            const isTransition = node.isTypeOf(META['Transition']);
            const isPlace = node.isTypeOf(META['Place']);
            if (isPlace || isTransition) {
                //right now we only interested in states...
                const elem = {
                    name: node.getAttribute('name'),
                    id: node.getId(),
                    outplaces: [], 
                    inplaces: [],
                    position: node.getRegistry('position'),
                };

                if ( isPlace ) {
                    pn.places[elementId] = elem;
                    elem.tokens = node.getAttribute('tokens');
                }
                else {
                    pn.transitions[elementId] = elem;
                }
            }
        });
    }

    PetriNetVisualizerControl.prototype._processLinks = function( 
        pnModel, meta, webgmeElementIds 
    ) {
        const self = this;
        const pn = pnModel;
        const elementIds = webgmeElementIds;
        const META = meta;
        elementIds.forEach(elementId => {
            const node = self._client.getNode(elementId);
            const isInplace = node.isTypeOf(META['InplaceArc']);
            const isOutplace = node.isTypeOf(META['OutplaceArc']);
            if (isInplace ) {
                const srcId = node.getPointerId( 'src' );
                const pl = pn.places[ srcId ];
                const plNode = self._client.getNode( srcId );
                const dstId = node.getPointerId( 'dst' );
                const tr = pn.transitions[ dstId ];
                const trNode = self._client.getNode( dstId );
                if ( tr ) {
                    pl.outplaces.push({
                        name: node.getAttribute( "name" ),
                        nodeName: trNode.getAttribute( "name" ),
                        node: dstId,
                    });
                }
                if ( pl ) {
                    tr.inplaces.push({
                        name: node.getAttribute( "name" ),
                        nodeName: plNode.getAttribute( "name" ),
                        node: srcId,
                    });
                }
            }
            else if ( isOutplace ) {
                const srcId = node.getPointerId( 'src' );
                const tr = pn.transitions[ srcId ];
                const trNode = self._client.getNode( srcId );
                const dstId = node.getPointerId( 'dst' );
                const pl = pn.places[ dstId ];
                const plNode = self._client.getNode( dstId );
                if ( pl ) {
                    tr.outplaces.push({
                        name: node.getAttribute( "name" ),
                        nodeName: plNode.getAttribute( "name" ),
                        node: dstId,
                    });
                }
                if ( tr ) {
                    pl.inplaces.push({
                        name: node.getAttribute( "name" ),
                        nameName: trNode.getAttribute( "name" ),
                        node: srcId,
                    });
                }
            }
        });
    }

    PetriNetVisualizerControl.prototype.setFireableEvents = function (events) {
        this._fireableEvents = events;
        if (events && events.length > 1) {
            // we need to fill the dropdow button with options
            this.$btnEventSelector.clear();
            events.forEach(event => {
                this.$btnEventSelector.addButton({
                    text: event,
                    title: 'fire event: '+ event,
                    data: {event: event},
                    clickFn: data => {
                        this._widget.fireEvent(data.event);
                    }
                });
            });
        } else if (events && events.length === 0) {
            this._fireableEvents = null;
        }

        this._displayToolbarItems();
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    PetriNetVisualizerControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
    };

    PetriNetVisualizerControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    PetriNetVisualizerControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    PetriNetVisualizerControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    PetriNetVisualizerControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
    };

    /* * * * * * * * * * Updating the toolbar * * * * * * * * * */
    PetriNetVisualizerControl.prototype._displayToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].show();
            }
            if (this._fireableEvents === null) {
                this.$btnEventSelector.hide();
                this.$btnSingleEvent.hide();
            } else if (this._fireableEvents.length == 1) {
                this.$btnEventSelector.hide();
            } else {
                this.$btnSingleEvent.hide();
            }
        } else {
            this._initializeToolbar();
        }
    };

    PetriNetVisualizerControl.prototype._hideToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].hide();
            }
        }
    };

    PetriNetVisualizerControl.prototype._removeToolbarItems = function () {

        if (this._toolbarInitialized === true) {
            for (var i = this._toolbarItems.length; i--;) {
                this._toolbarItems[i].destroy();
            }
        }
    };

    PetriNetVisualizerControl.prototype._initializeToolbar = function () {
        var self = this,
            toolBar = WebGMEGlobal.Toolbar;

        this._toolbarItems = [];

        this._toolbarItems.push(toolBar.addSeparator());

        /************** Go to hierarchical parent button ****************/
        this.$btnReachCheck = toolBar.addButton({
            title: 'Check state machine reachability properties',
            icon: 'glyphicon glyphicon-question-sign',
            clickFn: function (/*data*/) {
                const context = self._client.getCurrentPluginContext('ReachCheck',self._currentNodeId, []);
                // !!! it is important to fill out or pass an empty object as the plugin config otherwise we might get errors...
                context.pluginConfig = {};
                self._client.runServerPlugin(
                    'ReachCheck', 
                    context, 
                    function(err, result){
                        // here comes any additional processing of results or potential errors.
                        console.log('plugin err:', err);
                        console.log('plugin result:', result);
                });
            }
        });
        this._toolbarItems.push(this.$btnReachCheck);

        this.$btnResetPetriNet = toolBar.addButton({
            title: 'Reset simulator',
            icon: 'glyphicon glyphicon-fast-backward',
            clickFn: function (/*data*/) {
                self._widget.resetPetriNet();
            }
        });
        this._toolbarItems.push(this.$btnResetPetriNet);

        // when there are multiple events to choose from we offer a selector
        this.$btnEventSelector = toolBar.addDropDownButton({
            text: 'event'
        });
        this._toolbarItems.push(this.$btnEventSelector);
        this.$btnEventSelector.hide();

        // if there is only one event we just show a play button
        this.$btnSingleEvent = toolBar.addButton({
            title: 'Fire event',
            icon: 'glyphicon glyphicon-play',
            clickFn: function (/*data*/) {
                self._widget.fireEvent(self._fireableEvents[0]);
            }
        });
        this._toolbarItems.push(this.$btnSingleEvent);
        

        /************** Dropdown for event progression *******************/


        this._toolbarInitialized = true;
    };

    PetriNetVisualizerControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    return PetriNetVisualizerControl;
}

);
